# Generated by Django 3.2.15 on 2022-09-30 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_example_dns_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arecordmodel',
            name='ttl',
            field=models.IntegerField(default=14400, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='cnamerecordmodel',
            name='ttl',
            field=models.IntegerField(default=14400, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(2147483647)]),
        ),
    ]
